<a href="https://colab.research.google.com/github/Pushpalptha/Machine-Learning-programs/blob/main/MEACHINE_LEARNING_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


import glob
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/data lab1.csv')

In [ ]:
data

S.no        Name     Roll no Departement
0     1   k.pushpa   203T1A3101         Cai
1     2       latha  203T1A3102         cai
2     3      manasa  203T1A3103         cse
3     4       radha  203t1A3104         cse
4     5        rani  203T1A3105         cai
5     6      suguna  203T1A3106         cai
6     7        vani  203T1A3107         cse
7     8      harika  203T1A3108         cai
8     9       priya  203T1A3109         cse
9    10  pravillika  203T1a3110         cse

In [ ]:
concept=np.array(data)[:,:-1]

In [ ]:
concept

array([[1, 'k.pushpa ', '203T1A3101'],
       [2, 'latha', '203T1A3102'],
       [3, 'manasa', '203T1A3103'],
       [4, 'radha', '203t1A3104'],
       [5, 'rani', '203T1A3105'],
       [6, 'suguna', '203T1A3106'],
       [7, 'vani', '203T1A3107'],
       [8, 'harika', '203T1A3108'],
       [9, 'priya', '203T1A3109'],
       [10, 'pravillika', '203T1a3110']], dtype=object)

In [ ]:
target=np.array(data)[:,-1]

In [ ]:
target

array(['Cai', 'cai', 'cse', 'cse', 'cai', 'cai', 'cse', 'cai', 'cse',
       'cse'], dtype=object)

In [ ]:
def func(concept,target):
  for i, val in enumerate(target):
    if val=="yes":
      specific_hypothesis=concept[i].copy()
      print(specific_hypothesis)
      break
    count=0
    for i, val in enumerate(concept[i]):
      count=count+1
      print("concept=",concept[i])
      print("count=",count)
      if target [i]=="yes":
        print("target[i]=",target[i])
#print (len(specific_hypothesis))
        for x in range(len(specific_hypothesis)):
          print("x=",x)
          if val[x]!=specific_hypothesis[x]:
            #print("val[x]=",val[x])
            specific_hypothesis[x]='?'
            print("specific_hypothesis[x]=",specific_hypothesis)
          else:
            pass
            print(specific_hypothesis)
            return specific_hypothesis




In [ ]:
print("final specific hypothesis",func(concept,target))

concept= [1 'k.pushpa ' '203T1A3101']
count= 1
concept= [2 'latha' '203T1A3102']
count= 2
concept= [3 'manasa' '203T1A3103']
count= 3
concept= [1 'k.pushpa ' '203T1A3101']
count= 1
concept= [2 'latha' '203T1A3102']
count= 2
concept= [3 'manasa' '203T1A3103']
count= 3
concept= [1 'k.pushpa ' '203T1A3101']
count= 1
concept= [2 'latha' '203T1A3102']
count= 2
concept= [3 'manasa' '203T1A3103']
count= 3
concept= [1 'k.pushpa ' '203T1A3101']
count= 1
concept= [2 'latha' '203T1A3102']
count= 2
concept= [3 'manasa' '203T1A3103']
count= 3
concept= [1 'k.pushpa ' '203T1A3101']
count= 1
concept= [2 'latha' '203T1A3102']
count= 2
concept= [3 'manasa' '203T1A3103']
count= 3
concept= [1 'k.pushpa ' '203T1A3101']
count= 1
concept= [2 'latha' '203T1A3102']
count= 2
concept= [3 'manasa' '203T1A3103']
count= 3
concept= [1 'k.pushpa ' '203T1A3101']
count= 1
concept= [2 'latha' '203T1A3102']
count= 2
concept= [3 'manasa' '203T1A3103']
count= 3
concept= [1 'k.pushpa ' '203T1A3101']
count= 1
concept= [2 'la

In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv('/content/drive/MyDrive/data.csv')

In [ ]:
data

In [ ]:
concepts = np.array(data.iloc[:,0:-1])

In [ ]:
concepts

array([['sunny', 'warm', 'normal', 'strong', 'warm', 'same'],
       ['sunny', 'warm', 'high', 'strong', 'warm', 'same'],
       ['rainy', 'cold', 'high', 'strong', 'warm', 'same'],
       ['sunny', 'warm', 'high', 'strong', 'warm', 'same']], dtype=object)

In [ ]:
target = np.array(data.iloc[:,-1])

In [ ]:
target

array(['yes', 'yes', 'no', 'yes'], dtype=object)

In [ ]:
def learn(concepts, target):


    specific_h = concepts[0].copy()
    print("\nInitialization of specific_h and general_h")
    print(specific_h)

    general_h = [["?" for i in range(len(specific_h))] for i in range(len(specific_h))]
    print(general_h)

    for i, h in enumerate(concepts):

        if target[i] == "Yes":
            for x in range(len(specific_h)):

                if h[x] != specific_h[x]:
                    specific_h[x] = '?'
                    general_h[x][x] = '?'

        if target[i] == "No":
            for x in range(len(specific_h)):

                if h[x] != specific_h[x]:
                    general_h[x][x] = specific_h[x]
                else:
                    general_h[x][x] = '?'
        print("\nSteps of Candidate Elimination Algorithm",i+1)
        print(specific_h)
        print(general_h)


    indices = [i for i, val in enumerate(general_h) if val == ['?', '?', '?', '?', '?', '?']]
    for i in indices:

        general_h.remove(['?', '?', '?', '?', '?', '?'])
    return specific_h, general_h
s_final, g_final = learn(concepts, target)
print("\nFinal Specific_h:", s_final, sep="\n")
print("\nFinal General_h:", g_final, sep="\n")


Initialization of specific_h and general_h
['sunny' 'warm' 'normal' 'strong' 'warm' 'same']
[['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Steps of Candidate Elimination Algorithm 1
['sunny' 'warm' 'normal' 'strong' 'warm' 'same']
[['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Steps of Candidate Elimination Algorithm 2
['sunny' 'warm' 'normal' 'strong' 'warm' 'same']
[['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Steps of Candidate Elimination Algorithm 3
['sunny' 'warm' 'normal' 'strong' 'warm' 'same']
[['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 

Experiment-3

In [ ]:
import pandas as pd
from pandas import DataFrame

In [ ]:
df_tennis=pd.read_csv('/content/drive/MyDrive/outlook.csv')

In [ ]:
print("\n Given Play Tennis Data Set:\n\n",df_tennis)


 Given Play Tennis Data Set:

      out look temperature humidity    wind answer
0       sunny         hot     high    weak     no
1       sunny         hot     high  strong     no
2   over cast         hot     high    weak    yes
3        rain        mild     high    weak    yes
4        rain        cool   normal    weak    yes
5        rain        cool   normal  strong     no
6   over cast        cool   normal  strong    yes
7       sunny        mild     high    weak     no
8       sunny        cool   normal    weak    yes
9        rain        mild   normal  strong    yes
10      sunny        mild   normal  strong    yes
11  over cast        mild     high    weak    yes
12  over cast         hot   normal  strong    yes
13       rain        mild     high    weak     no


In [ ]:
df_tennis.keys()[0]

'out look'

In [ ]:
def entropy(probs):
    import math
    return sum( [-prob*math.log(prob, 2) for prob in probs] )
def entropy_of_list(a_list):
    from collections import Counter
    cnt = Counter(x for x in a_list)
    num_instances = len(a_list)*1.0
    print("\n Number of Instances of the Current Sub Class is {0}:".format(num_instances ))
    probs = [x / num_instances for x in cnt.values()]
    print("\n Classes:",min(cnt),max(cnt))
    print(" \n Probabilities of Class {0} is {1}:".format(min(cnt),min(probs)))
    print(" \n Probabilities of Class {0} is {1}:".format(max(cnt),max(probs)))
    return entropy(probs)



In [ ]:
print("\n  INPUT DATA SET FOR ENTROPY CALCULATION:\n", df_tennis['out look'])

total_entropy = entropy_of_list(df_tennis['out look'])

print("\n Total Entropy of PlayTennis Data Set:",total_entropy)



  INPUT DATA SET FOR ENTROPY CALCULATION:
 0         sunny
1         sunny
2     over cast
3          rain
4          rain
5          rain
6     over cast
7         sunny
8         sunny
9          rain
10        sunny
11    over cast
12    over cast
13         rain
Name: out look, dtype: object

 Number of Instances of the Current Sub Class is 14.0:

 Classes: over cast sunny
 
 Probabilities of Class over cast is 0.2857142857142857:
 
 Probabilities of Class sunny is 0.35714285714285715:

 Total Entropy of PlayTennis Data Set: 1.5774062828523452


In [ ]:
import random
from math import exp
from random import seed


In [ ]:
def initialize_network(n_inputs, n_hidden, n_outputs):
    network = list()
    hidden_layer = [{'weights':[random.uniform(-0.5,0.5) for i in range(n_inputs + 1)]} for i in range(n_hidden)]
    network.append(hidden_layer)
    output_layer = [{'weights':[random.uniform(-0.5,0.5) for i in range(n_hidden + 1)]} for i in range(n_outputs)]
    network.append(output_layer)
    i= 1
    print("\n The initialised Neural Network:\n")
    for layer in network:
        j=1
        for sub in layer:
            print("\n Layer[%d] Node[%d]:\n" %(i,j),sub)
            j=j+1
        i=i+1
    return network
def activate(weights, inputs):
    activation = weights[-1]
    for i in range(len(weights)-1):
        activation += weights[i] * inputs[i]
    return activation
def transfer(activation):
    return 1.0 / (1.0 + exp(-activation))
def forward_propagate(network, row):
    inputs = row
    for layer in network:
        new_inputs = []
        for neuron in layer:
            activation = activate(neuron['weights'], inputs)
            neuron['output'] = transfer(activation)
            new_inputs.append(neuron['output'])
        inputs = new_inputs
    return inputs
def transfer_derivative(output):
    return output * (1.0 - output)
def backward_propagate_error(network, expected):
    for i in reversed(range(len(network))):
        layer = network[i]
        errors = list()

        if i != len(network)-1:
            for j in range(len(layer)):
                error = 0.0
                for neuron in network[i + 1]:
                    error += (neuron['weights'][j] * neuron['delta'])
                errors.append(error)
        else:
            for j in range(len(layer)):
                neuron = layer[j]
                errors.append(expected[j] - neuron['output'])

        for j in range(len(layer)):
            neuron = layer[j]
            neuron['delta'] = errors[j] * transfer_derivative(neuron['output'])
def update_weights(network, row, l_rate):
    for i in range(len(network)):
        inputs = row[:-1]
        if i != 0:
            inputs = [neuron['output'] for neuron in network[i - 1]]
        for neuron in network[i]:
            for j in range(len(inputs)):
                neuron['weights'][j] += l_rate * neuron['delta'] * inputs[j]
            neuron['weights'][-1] += l_rate * neuron['delta']
def train_network(network, train, l_rate, n_epoch, n_outputs):

    print("\n Network Training Begins:\n")

    for epoch in range(n_epoch):
        sum_error = 0
        for row in train:
            outputs = forward_propagate(network, row)
            expected = [0 for i in range(n_outputs)]
            expected[row[-1]] = 1
            sum_error += sum([(expected[i]-outputs[i])**2 for i in range(len(expected))])
            backward_propagate_error(network, expected)
            update_weights(network, row, l_rate)
        print('>epoch=%d, lrate=%.3f, error=%.3f' % (epoch, l_rate, sum_error))

    print("\n Network Training Ends:\n")
seed(2)
dataset = [[2.7810836,2.550537003,0],
    [1.465489372,2.362125076,0],
    [3.396561688,4.400293529,0],
    [1.38807019,1.850220317,0],
    [3.06407232,3.005305973,0],
    [7.627531214,2.759262235,1],
    [5.332441248,2.088626775,1],
    [6.922596716,1.77106367,1],
    [8.675418651,-0.242068655,1],
    [7.673756466,3.508563011,1]]

print("\n The input Data Set :\n",dataset)
n_inputs = len(dataset[0]) - 1
print("\n Number of Inputs :\n",n_inputs)
n_outputs = len(set([row[-1] for row in dataset]))
print("\n Number of Outputs :\n",n_outputs)
network = initialize_network(n_inputs, 2, n_outputs)
train_network(network, dataset, 0.5, 20, n_outputs)
print("\n Final Neural Network :")
i= 1
for layer in network:
    j=1
    for sub in layer:
        print("\n Layer[%d] Node[%d]:\n" %(i,j),sub)
        j=j+1
    i=i+1


 The input Data Set :
 [[2.7810836, 2.550537003, 0], [1.465489372, 2.362125076, 0], [3.396561688, 4.400293529, 0], [1.38807019, 1.850220317, 0], [3.06407232, 3.005305973, 0], [7.627531214, 2.759262235, 1], [5.332441248, 2.088626775, 1], [6.922596716, 1.77106367, 1], [8.675418651, -0.242068655, 1], [7.673756466, 3.508563011, 1]]

 Number of Inputs :
 2

 Number of Outputs :
 2

 The initialised Neural Network:


 Layer[1] Node[1]:
 {'weights': [0.4560342718892494, 0.4478274870593494, -0.4434486322731913]}

 Layer[1] Node[2]:
 {'weights': [-0.41512800484107837, 0.33549887812944956, 0.2359699890685233]}

 Layer[2] Node[1]:
 {'weights': [0.1697304014402209, -0.1918635424108558, 0.10594416567846243]}

 Layer[2] Node[2]:
 {'weights': [0.10680173364083789, 0.08120401711200309, -0.3416171297451944]}

 Network Training Begins:

>epoch=0, lrate=0.500, error=5.278
>epoch=1, lrate=0.500, error=5.122
>epoch=2, lrate=0.500, error=5.006
>epoch=3, lrate=0.500, error=4.875
>epoch=4, lrate=0.500, error

In [ ]:
path='/content/drive/MyDrive/data.txt'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


def splitDataset(dataset, splitRatio):
    trainSize = int(len(dataset) * splitRatio)
    trainSet = []
    copy = list(dataset)
    while len(trainSet) < trainSize:
        index = random.randrange(len(copy)) # random index
        trainSet.append(copy.pop(index))
    return [trainSet, copy]



In [ ]:
def separateByClass(dataset):
    separated = {}
    for i in range(len(dataset)):
        vector = dataset[i]
        if (vector[-1] not in separated):
            separated[vector[-1]] = []
        separated[vector[-1]].append(vector)
    return separated



In [ ]:
def mean(numbers):
    return sum(numbers)/float(len(numbers))


In [ ]:
def stdev(numbers):
    avg = mean(numbers)
    variance = sum([pow(x-avg,2) for x in numbers])/float(len(numbers)-1)
    return math.sqrt(variance)


In [ ]:
def summarize(dataset):
    summaries = [(mean(attribute), stdev(attribute)) for attribute in zip(*dataset)]
    del summaries[-1]
    return summaries


In [ ]:
def summarizeByClass(dataset):
    separated = separateByClass(dataset)
    summaries = {}
    for classValue, instances in separated.items():
        summaries[classValue] = summarize(instances)
    return summaries


In [ ]:
def calculateProbability(x, mean, stdev):
    exponent = math.exp(-(math.pow(x-mean,2)/(2*math.pow(stdev,2))))
    return (1 / (math.sqrt(2*math.pi) * stdev)) * exponent


In [ ]:
def predict(summaries, inputVector):
    probabilities = calculateClassProbabilities(summaries, inputVector)
    bestLabel, bestProb = None, -1
    for classValue, probability in probabilities.items():
        if bestLabel is None or probability > bestProb:
            bestProb = probability
            bestLabel = classValue
    return bestLabel



In [ ]:
def getPredictions(summaries, testSet):
    predictions = []
    for i in range(len(testSet)):
        result = predict(summaries, testSet[i])
        predictions.append(result)
    return predictions


In [ ]:
def getAccuracy(testSet, predictions):
    correct = 0
    for i in range(len(testSet)):
        if testSet[i][-1] == predictions[i]:
            correct += 1
    return (correct/float(len(testSet))) * 100.0


In [ ]:
def main():
    filename = '/content/drive/MyDrive/5-dataset.csv'
    splitRatio = 0.67
    dataset = loadcsv(filename)

    #print("\n The Data Set :\n",dataset)
    print("\n The length of the Data Set : ",len(dataset))

    print("\n The Data Set Splitting into Training and Testing \n")
    trainingSet, testSet = splitDataset(dataset, splitRatio)

    print('\n Number of Rows in Training Set:{0} rows'.format(len(trainingSet)))
    print('\n Number of Rows in Testing Set:{0} rows'.format(len(testSet)))

    print("\n First Five Rows of Training Set:\n")
    for i in range(0,5):
        print(trainingSet[i],"\n")

    print("\n First Five Rows of Testing Set:\n")
    for i in range(0,5):
        print(testSet[i],"\n")
    summaries = summarizeByClass(trainingSet)
    print("\n Model Summaries:\n",summaries)

    predictions = getPredictions(summaries, testSet)
    print("\nPredictions:\n",predictions)

    accuracy = getAccuracy(testSet, predictions)
    print('\n Accuracy: {0}%'.format(accuracy))
    main()



In [ ]:
import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
    getattr(ssl, '_create_unverified_context', None)):
    ssl._create_default_https_context = ssl._create_unverified_context

from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train', shuffle=True)
x = len(twenty_train.target_names)
print("\n The number of categories:",x)
print("\n The %d Different Categories of 20Newsgroups\n" %x)
i=1
for cat in twenty_train.target_names:
    print("Category[%d]:" %i,cat)
    i=i+1
print("\n Length of training data is",len(twenty_train.data))
print("\n Length of file names is ",len(twenty_train.filenames))

print("\n The Content/Data of First File is :\n")

print(twenty_train.data[0])



 The number of categories: 20

 The 20 Different Categories of 20Newsgroups

Category[1]: alt.atheism
Category[2]: comp.graphics
Category[3]: comp.os.ms-windows.misc
Category[4]: comp.sys.ibm.pc.hardware
Category[5]: comp.sys.mac.hardware
Category[6]: comp.windows.x
Category[7]: misc.forsale
Category[8]: rec.autos
Category[9]: rec.motorcycles
Category[10]: rec.sport.baseball
Category[11]: rec.sport.hockey
Category[12]: sci.crypt
Category[13]: sci.electronics
Category[14]: sci.med
Category[15]: sci.space
Category[16]: soc.religion.christian
Category[17]: talk.politics.guns
Category[18]: talk.politics.mideast
Category[19]: talk.politics.misc
Category[20]: talk.religion.misc

 Length of training data is 11314

 Length of file names is  11314

 The Content/Data of First File is :

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there coul

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(twenty_train.data)
print("\n(Target Length , Distinct Words):",X_train_counts.shape)
print("\n Frequency of the word algorithm:", count_vect.vocabulary_.get('algorithm'))



(Target Length , Distinct Words): (11314, 130107)

 Frequency of the word algorithm: 27366


In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape


(11314, 130107)

In [ ]:
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']


In [ ]:
pip install pgmpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.9 MB 7.1 MB/s 


In [ ]:
import pandas as pd
data=pd.read_csv("/content/drive/MyDrive/dataset.csv")
heart_disease=pd.DataFrame(data)
print(heart_disease)
from pgmpy.models import BayesianModel
model=BayesianModel([
('age','Lifestyle'),
('Gender','Lifestyle'),
('Family','heartdisease'),
('diet','cholestrol'),
('Lifestyle','diet'),
('cholestrol','heartdisease'),
('diet','cholestrol')
])



   age  gender  family  diet  lifestyle  cholestrol  heart diesease
0    0       0       1     1          3           0               0
1    0       1       1     0          2           1               1
2    1       0       0     0          4           1               0
3    2       1       0     1          2           0               0
4    3       0       1     1          3           1               1
5    4       1       0     0          3           0               1


/usr/local/lib/python3.8/dist-packages/pgmpy/models/BayesianModel.py:8: FutureWarning: BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
  warnings.warn(


In [ ]:
from pgmpy.estimators import MaximumLikelihoodEstimator
model.fit(heart_disease, estimator=MaximumLikelihoodEstimator)

from pgmpy.inference import VariableElimination
Heart Disease_infer = VariableElimination(model)



In [ ]:
from sklearn.cluster import KMeans
from sklearn import preprocessing
from sklearn.mixture import GaussianMixture
from sklearn.datasets import load_iris
import sklearn.metrics as sm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
dataset=load_iris()


In [ ]:
X=pd.DataFrame(dataset.data)
X.columns=['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width']
y=pd.DataFrame(dataset.target)
y.columns=['Targets']
print(X)


In [ ]:
plt.figure(figsize=(14,7))
colormap=np.array(['red','lime','black'])
plt.subplot(1,3,1)
plt.scatter(X.Petal_Length,X.Petal_Width,c=colormap[y.Targets],s=40)
plt.title('Real')




In [ ]:
plt.subplot(1,3,2)
model=KMeans(n_clusters=3)
model.fit(X)
predY=np.choose(model.labels_,[0,1,2]).astype(np.int64)
plt.scatter(X.Petal_Length,X.Petal_Width,c=colormap[predY],s=40)
plt.title('KMeans')



In [ ]:
scaler=preprocessing.StandardScaler()
scaler.fit(X)
xsa=scaler.transform(X)
xs=pd.DataFrame(xsa,columns=X.columns)
gmm=GaussianMixture(n_components=3)
gmm.fit(xs)
y_cluster_gmm=gmm.predict(xs)
plt.subplot(1,3,3)
plt.scatter(X.Petal_Length,X.Petal_Width,c=colormap[y_cluster_gmm],s=40)
plt.title('GMM Classification')


In [ ]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.model_selection import train_test_split
iris_dataset=load_iris()


In [ ]:
print("\n IRIS FEATURES \ TARGET NAMES: \n ", iris_dataset.target_names)
for i in range(len(iris_dataset.target_names)):
    print("\n[{0}]:[{1}]".format(i,iris_dataset.target_names[i]))

print("\n IRIS DATA :\n",iris_dataset["data"])


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris_dataset["data"], iris_dataset["target"], random_state=0)

print("\n Target :\n",iris_dataset["target"])
print("\n X TRAIN \n", X_train)
print("\n X TEST \n", X_test)
print("\n Y TRAIN \n", y_train)
print("\n Y TEST \n", y_test)
kn = KNeighborsClassifier(n_neighbors=1)
kn.fit(X_train, y_train)


In [ ]:


print("\n Predicted target value: {}\n".format(prediction))
print("\n Predicted feature name: {}\n".format
    (iris_dataset["target_names"][prediction]))

i=1
x= X_test[i]
x_new = np.array([x])
print("\n XNEW \n",x_new)

for i in range(len(X_test)):
    x = X_test[i]
    x_new = np.array([x])
    prediction = kn.predict(x_new)
    print("\n Actual : {0} {1}, Predicted :{2}{3}".format(y_test[i],iris_dataset["target_names"][y_test[i]],prediction,iris_dataset["target_names"][prediction]))



NameError: ignored

In [ ]:
import pandas as pd
data=pd.read_csv("/content/drive/MyDrive/heartdisease1.csv")
heartdisease=pd.DataFrame(data)
print(heartdisease)


    age  gender  family  diet  lifestyle  cholestrol  heartdisease
0     0       0       1     1          3           0             1
1     0       1       1     1          3           0             1
2     1       0       0     0          2           1             1
3     4       0       1     1          3           2             0
4     3       1       1     0          0           2             0
5     2       0       1     1          1           0             1
6     4       0       1     0          2           0             1
7     0       0       1     1          3           0             1
8     3       1       1     0          0           2             0
9     1       1       0     0          0           2             1
10    4       1       0     1          2           0             1
11    4       0       1     1          3           2             0
12    2       1       0     0          0           0             0
13    2       0       1     1          1           0          

In [ ]:
pip install pgmpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from pgmpy.models import BayesianModel
model=BayesianModel([('age','lifestyle'),('gender','lifestyle'),('family','heartdisease'),('diet','cholestrol'),('lifestyle','diet'),('cholestrol','heartdisease'),('diet','cholestrol')])
from pgmpy.estimators import MaximumLikelihoodEstimator
model.fit(heartdisease,estimator=MaximumLikelihoodEstimator)
from pgmpy.inference import VariableElimination


/usr/local/lib/python3.8/dist-packages/pgmpy/models/BayesianModel.py:8: FutureWarning: BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
  warnings.warn(


In [ ]:
heartdisease_infer = VariableElimination(model)
print('For age Enter { SuperSeniorCitizen:0, SeniorCitizen:1, MiddleAged:2, Youth:3, Teen:4 }')
print('For gender Enter { Male:0, Female:1 }')
print('For family history Enter { yes:1, No:0 }')
print('For diet Enter { High:0, Medium:1 }')
print('For lifestyle Enter { Athlete:0, Active:1, Moderate:2, Sedentary:3 }')
print('For cholesterol Enter { High:0, BorderLine:1, Normal:2 }')


For age Enter { SuperSeniorCitizen:0, SeniorCitizen:1, MiddleAged:2, Youth:3, Teen:4 }
For gender Enter { Male:0, Female:1 }
For family history Enter { yes:1, No:0 }
For diet Enter { High:0, Medium:1 }
For lifestyle Enter { Athlete:0, Active:1, Moderate:2, Sedentary:3 }
For cholesterol Enter { High:0, BorderLine:1, Normal:2 }


In [ ]:
q = heartdisease_infer.query(variables=['heartdisease'], evidence={'age':int(input('Enter age :')),'gender':int(input('Enter gender :')),'family':int(input('Enter family history :')),'diet':int(input('Enter diet :')),'lifestyle':int(input('Enter lifestyle :')),'cholestrol':int(input('Enter cholestrol :'))})
print(q)


Enter age :0
Enter gender :1
Enter family history :1
Enter diet :1
Enter lifestyle :3
Enter cholestrol :0
+-----------------+---------------------+
| heartdisease    |   phi(heartdisease) |
+=================+=====================+
| heartdisease(0) |              0.0000 |
+-----------------+---------------------+
| heartdisease(1) |              1.0000 |
+-----------------+---------------------+


In [ ]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.model_selection import train_test_split


In [ ]:
iris_dataset=load_iris()
print("\n IRIS FEATURES \ TARGET NAMES: \n",iris_dataset.target_names)



 IRIS FEATURES \ TARGET NAMES: 
 ['setosa' 'versicolor' 'virginica']


In [ ]:
for i in range(len(iris_dataset.target_names)):
  print("\n[{0}]:[{1}]".format(i,iris_dataset.target_names[i]))



[0]:[setosa]

[1]:[versicolor]

[2]:[virginica]


In [ ]:
print("\n IRIS DATA :\n",iris_dataset["data"])



 IRIS DATA :
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(iris_dataset["data"],iris_dataset["target"],random_state=0)
print("\n Target :\n",iris_dataset["target"])
print("\n X TRAIN \n",X_train)
print("\n X TEST \n",X_test)
print("\n Y TRAIN \n",y_train)
print("\n Y TEST \n",y_test)
kn=KNeighborsClassifier(n_neighbors=1)
kn.fit(X_train,y_train)



 Target :
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

 X TRAIN 
 [[5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]
 [5.  3.5 1.6 0.6]
 [5.4 3.7 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.5 3.  5.5 1.8]
 [6.7 3.3 5.7 2.5]
 [6.  2.2 5.  1.5]
 [6.7 2.5 5.8 1.8]
 [5.6 2.5 3.9 1.1]
 [7.7 3.  6.1 2.3]
 [6.3 3.3 4.7 1.6]
 [5.5 2.4 3.8 1.1]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [4.9 2.5 4.5 1.7]
 [6.3 2.5 5.  1.9]
 [7.  3.2 4.7 1.4]
 [6.5 3.  5.2 2. ]
 [6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]
 [6.1 3.  4.6 1.4]
 [7.2 3.2 6.  1.8]
 [5.3 3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7

KNeighborsClassifier(n_neighbors=1)

In [ ]:
x_new=np.array([[5,2.9,1,0.2]])
print("\n XNEW \n",x_new)
prediction=kn.predict(x_new)
print("\n Predicted target value:{}\n".format(prediction))
print("\n Predicted feature name:{}\n".format(iris_dataset["target_names"][prediction]))



 XNEW 
 [[5.  2.9 1.  0.2]]

 Predicted target value:[0]


 Predicted feature name:['setosa']



In [ ]:
i=1
x=X_test[i]
x_new=np.array([x])
print("\n XNEW \n",x_new)



 XNEW 
 [[6.  2.2 4.  1. ]]


In [ ]:
for i in range(len(X_test)):
  x=X_test[i]
  x_new=np.array([x])
  prediction=kn.predict(x_new)
  print("\n Actual : {0} {1}, Predicted :{2}{3}".format(y_test[i],iris_dataset["target_names"][y_test[i]],prediction,iris_dataset["target_names"][prediction]))


 Actual : 2 virginica, Predicted :[2]['virginica']

 Actual : 1 versicolor, Predicted :[1]['versicolor']

 Actual : 0 setosa, Predicted :[0]['setosa']

 Actual : 2 virginica, Predicted :[2]['virginica']

 Actual : 0 setosa, Predicted :[0]['setosa']

 Actual : 2 virginica, Predicted :[2]['virginica']

 Actual : 0 setosa, Predicted :[0]['setosa']

 Actual : 1 versicolor, Predicted :[1]['versicolor']

 Actual : 1 versicolor, Predicted :[1]['versicolor']

 Actual : 1 versicolor, Predicted :[1]['versicolor']

 Actual : 2 virginica, Predicted :[2]['virginica']

 Actual : 1 versicolor, Predicted :[1]['versicolor']

 Actual : 1 versicolor, Predicted :[1]['versicolor']

 Actual : 1 versicolor, Predicted :[1]['versicolor']

 Actual : 1 versicolor, Predicted :[1]['versicolor']

 Actual : 0 setosa, Predicted :[0]['setosa']

 Actual : 1 versicolor, Predicted :[1]['versicolor']

 Actual : 1 versicolor, Predicted :[1]['versicolor']

 Actual : 0 setosa, Predicted :[0]['setosa']

 Actual : 0 setosa, P